### ISSUE TITLE
Question... How does Jinq guesses the operators in Lambdas

### ISSUE THREAD

**Issue by bsbodden** [my2iu/Jinq#101]
This is just curiosity... How does the Lambda analyser parses a lambda like:

```
JinqStream<Integer> customers = streams.streamAll(em, Customer.class)
   .select(c -> c.getDebt() + c.getSalary() * 2);
```

How does it extract the `+` and `*` from the SerializedLambda? To get `"SELECT A.debt + A.salary * 2 FROM Customer A"`?

Thanks for any insights... Great library!

**Comment by my2iu** [comment]
Here’s a video where I walk through the translation of a simple query

https://www.youtube.com/watch?v=JqCnZFzTR2I
