### ISSUE TITLE
How to get the total count after group by?

### ISSUE THREAD

**Issue by zdu-strong** [my2iu/Jinq#106]
When there is no group by, I directly call .count() to get the total number of entries.

After the group by, I call .count(), which throws an exception:
java.lang.IllegalArgumentException: Could not translate code to a query.

How to get the total count after group by?

**Comment by my2iu** [comment]
I’m not sure what you mean by total count. If you want the count of the elements of each group, you can just follow the example here:

http://www.jinq.org/docs/queries.html#N67306

Counts of other things—like the number of groups or counts of elements across all the groups—those can’t be represented in SQL, so there is no way to do that without issuing a separate query.

**Comment by zdu-strong** [comment]
When I use mysql database, I use SQL_CALC_FOUND_ROWS FOUND_ROWS function to get the total number of groups.
It is very convenient to use.

![MysqlDialect](https://user-images.githubusercontent.com/48673442/221346443-2ace6fed-cbef-4cb1-ab44-80a17ba7d45d.png)

![totalCount](https://user-images.githubusercontent.com/48673442/221346831-5b511877-54de-4473-b9f4-daeccd264f45.png)

Now, I'm preparing to use the spanner database, but I don't find the same function in spanner, which makes me very troubled.

**Comment by zdu-strong** [comment]
"Counts of other things—like the number of groups or counts of elements across all the groups—those can’t be represented in SQL, so there is no way to do that without issuing a separate query or grabbing the data and then manually querying the result"

How did you do this kind of query? Can you give me an example?

**Comment by zdu-strong** [comment]
Share my pagination experience when using Jinq and mysql database.

The following is the usage, pagination processing inside the PaginationModel, even the stream of group by is OK.
![pagination](https://user-images.githubusercontent.com/48673442/221361720-eb0fcaff-fe50-43cf-a138-abb0bf2e578f.png)

If someone wants to refer to the source code, please check my project (https://github.com/zdu-strong/Technical_Backup/tree/master/springboot).
