### ISSUE TITLE
How to get the number of groups by issuing a separate query after group by?

### ISSUE THREAD

**Issue by zdu-strong** [my2iu/Jinq#108]
I'm preparing to use the spanner database, but I've encountered a problem, please help me.

**Comment by my2iu** [comment]
I’ve never used Spanner, and I’m not sure if Jinq even works with Spanner. But assuming Spanner is supposed to work like SQL, then you can

- use distinct and then count to count the number of groups http://www.jinq.org/docs/queries.html#N67275
- if you’re using a query to fetch the groups anyway, then once you’ve called toList() to execute the query and store the results in memory, then just call size() to get the number of groups.

**Comment by zdu-strong** [comment]
Thank you for your help.

**Comment by zdu-strong** [comment]
Sharing my experience, I am collecting information and have not verified it yet.
Spanner database supports PostgreSQL dialect, and PostgreSQL supports the method of obtaining the total number of records.
It may be used to solve the problem of getting the total number of the groups.

![PostgreSQL](https://user-images.githubusercontent.com/48673442/221488681-950d09b2-c9ec-4270-bcda-bce44dab678d.png)

**Comment by zdu-strong** [comment]
In Spanner's GoogleSQL dialect, use count(*) OVER () to get the total number of rows, even after group by. It cannot be used in local emulators spanner, and needs to be compatible.

My project has added support for spanner, anyone who needs a reference can view my project (https://github.com/zdu-strong/Technical_Backup/tree/spanner/springboot).

Todo List:
1. Add liquibase support for spanner.
