### ISSUE TITLE
Support java v21

### ISSUE THREAD

**Issue by zdu-strong** [my2iu/Jinq#109]
When my project is run in java v21, an exception will occur.

![java v21](https://github.com/my2iu/Jinq/assets/48673442/c42e54d2-b6b2-4cc7-9adb-d2c745c8d1f5)

**Comment by zdu-strong** [comment]
My Repository: https://github.com/zdu-strong/Project-Java-21-Test.git
Require Enviroment: java v21
Run Command:  ./mvn clean test

**Comment by my2iu** [comment]
Sorry for the delay. I was waiting for JDK21 to published by Adoptium first. But they're available now, so I'll try to work on it over the next few weeks.

**Comment by zdu-strong** [comment]
Thank you for your support.

**Comment by my2iu** [comment]
I've deployed the new 1.8.36 and 2.0.1 releases of Jinq to Maven Central that should support JDK21. I'll update the website with those releases later on

**Comment by zdu-strong** [comment]
> I've deployed the new 1.8.36 and 2.0.1 releases of Jinq to Maven Central that should support JDK21. I'll update the website with those releases later on

Thank you very much!
