### ISSUE TITLE
How get primaryKeys By Jinq ?

### ISSUE THREAD

**Issue by flyzb618** [my2iu/Jinq#19]
I add below code into JinqJPAStreamProvider:
      public JPAJinqStream selectPrimaryKeys(JPAJinqStream base) {
		JPAQueryComposer jpaComposer = ((QueryJPAJinqStream) base).jpaComposer;
		SelectFromWhere query = (SelectFromWhere) jpaComposer.query;
		SelectFromWhere copy = query.shallowCopy();
		org.jinq.jpa.jpqlquery.RowReader reader = copy.getRowReader();
		ColumnExpressions columnExpressions = new ColumnExpressions(reader);
		columnExpressions.columns.add(new ReadFieldExpression(
				((SelectOnly) (copy)).cols.getOnlyColumn(), "id"));
		copy.cols = columnExpressions;
		return new QueryJPAJinqStream(JPAQueryComposer.findAllEntities(
				metamodel, cachedQueries, lambdaAnalyzer,
				jpqlQueryTransformConfigurationFactory, jpaComposer.em, hints,
				copy));
	}

But  there is erro in "toList" when I run below code , why?
       JPAJinqStream<Object> idStream =new JinqJPAStreamProvider(getEntityManager()
					.getMetamodel()).selectPrimaryKeys(stream);			
	List<Object> idList = idStream.toList() ;

**Comment by my2iu** [comment]
What is the error that you're seeing?

To be honest, it seems like you're not really taking advantage of Jinq's features here. You should simply do a:

     stream.select( obj -> obj.getId() ).toList();

If necessary, you should make sure that all of your entities inherit from a common base class that has a `getId()` method on it (plus, do all the necessary JPA magic to get JPA to understand that hierarchy properly)

**Comment by my2iu** [comment]
I haven't heard of any further details on this issue, so I am marking it resolved.
