### ISSUE TITLE
How to do (jinq and JPA, and spring) supporting transaction configuration

### ISSUE THREAD

**Issue by mysoko** [my2iu/Jinq#2]
The inside of the Java or more and spring binding, relevant information display configuration?

Added, in fact, the inside of the scala slick is good enough, but Java jinq gave us the same.

**Comment by RomanSubrychak** [comment]
Is that posible to get that source code example from that http://www.jinq.org/docs/spring.html documentation

**Comment by my2iu** [comment]
I'm not sure whether I still have the code sitting around. It's basically just the [Spring Pet Clinic](https://github.com/spring-projects/spring-petclinic) but with the code from the Jinq documentation pasted in. If it's really important, I can try to recreate it.
