### ISSUE TITLE
Create and use Pojos in queries

### ISSUE THREAD

**Issue by oberien** [my2iu/Jinq#24]
Currently one has to use `Pair` or `Tuple2,3,...` to compine multiple values. Would it be possible to support creating and using (immutable) POJOs?

This would be extremely helpful for One-To-One mapped joins, as no `Collector` is needed to be written. It would also simplify reading huge queries, as `foo.bar().baz().qux` is easier to read and keep in mind than `pair.getOne().getOne().qux`.

**Comment by my2iu** [comment]
This is possible, but the syntax issues with Java means that the result will be a bit of a mess for programmers and for Jinq, so I'm not really inclined to implement it.

I am not sure what you mean by needing Collectors for 1:1 mapped joins, since you can just traverse them in Jinq without needing to do anything special.

```stream.select(a -> return new Tuple3<>(a, a.bar(), a.bar().baz()) )```

or something like that.

**Comment by oberien** [comment]
Though it is true that I don't need a collector for 1:1 queries, but could use `map` instead, my main point here is that it is hard to keep in mind, which element of a huge Tuple (e.g. Tuple5) is what. For rather complex queries it would be nice to be able to use custom pojos with proper names. That way it is easier to keep in mind which field is what.

If returning the pojo from the query is rather complex, you could force the returned object of the query to be a Pair/Tuple again.

**Comment by my2iu** [comment]
I agree it would be nice, but it is not as good as you think it would be. C#'s LINQ has special syntax for creating light-weight objects for cases like this. For Java, you would have to create an entire class with setters, getters, and a constructor before you could use it in a query. It's a real hassle.

**Comment by oberien** [comment]
Coming back to this issue, I currently have a very complex query. It's return value is `Tuple8<A,B,Pair<C,D>,E,F,G,H,Tuple3<I,J,K>>`. The query itself looks very nice and clean, easily readable and understandable by everyone. The appropriate SQL-Query looks like garbage and needs about 3 days to figure out what it's doing. But in the query and collector using `t.getEight().getTwo()` to get the 9th element, and keeping track of all the elements and their positions, is very complicated, especially if two or more columns contain the same data type.

It is true, that C#'s dynamic typing is ideal for that case, but in Java POJOs can be created rather easily using [lombok](https://projectlombok.org/)'s [`@Data`](https://projectlombok.org/features/Data.html) Annotation. I would very much prefer to have the overhead of defining the POJO-class and using that inside the query instead of needing to memorize which position responds to which item.

For example it would be very convenient to use the following classes:
```java
@Data
class CD {
    /** doc for field c **/
    C c;
    /** doc for field d *//
    D d;
}
@Data
class Res {
    /** doc for field a **/
    A a;
    /** doc for field b **/
    B b;
    /** doc for field cd **/
    CD cd,
    [...]
}
```
Could you please give me an inside of how complex it would be to implement this into Jinq and which problems could arise? Which complications did you mean with
> the syntax issues with Java means that the result will be a bit of a mess for programmers and for Jinq

One leftover question would be if it was possible to return the POJO out of the query to use it in the collector, or if the POJO can only be used as immediate representation in the query and a mapping back to a tuple would be required as last step in the query.

**Comment by aVolpe** [comment]
lombok and jinq are a very useful couple (with the @Data and @AllArgsConstructor).

It's trivial to create classes for your complex queries and let JPA do all the mappings, something like this

```java
String complexQuery = "SELECT new " + MyCustomClass.class.getName() + " ( params ) FROM ... rest of query ";
List<MyCustomClass> result = getEm().createQuery(complexQuery, MyCustomClass.class).getResultList();
```

And `MyCustomClass` something like:

```java
@Data
@AllArgsConstructor
static class MyCustomClass {
    // args without getters and setters.
}
```

**Comment by my2iu** [comment]
After thinking about it a bit, I might be able to do a partial hack that will do some/most of what you want. Let me tinker a bit over the weekend and see what I can come up with.

**Comment by aVolpe** [comment]
@my2iu if you provide a basic introduction of what to change or where to look, I can make you a pull request.

**Comment by my2iu** [comment]
I've implemented some sort of support for custom tuple objects. There are three test cases that start with `testCustomTuple` that you can see in the test file below:

https://github.com/my2iu/Jinq/blob/master/jinq-jpa/test/org/jinq/jpa/JinqJPATypesTest.java#L601

Would this work for you?

I'm actually away from the computer that I use for building and packaging Jinq releases, so you'll need to wait a few days for me to make a release of it.

**Comment by ztane** [comment]
@my2iu seems that you could use a Travis-CI setup. I've got one for some of my Python packages so that when I push to "release" branch, Travis not only tests and builds but uploads to public package repository automatically as well.

**Comment by oberien** [comment]
This looks very nice!

I think this is going to be too complex, but would it be possible to use POJOs without registering them? AFAIU you have a switch on classes, which are defined in Jinq. Whenever a class is used in a query, you react according to that switch. Is it possible if a class is used in a query, but not known to Jinq, to check, if it is an POJO and if so, add it internally as POJO to the list of custom tuple-types? This POJO check could either be done (incompletely) with reflection testing if the Class has only a constructor and getters/setters (test by name), or a complete check with symEx to verify, that the constructor and setters are only setting internal values provided as arguments and getters, which only consist of `return value`.

I may ask for too much, but would it also be possible to have multiple constructors for one class? That way one could format the query during the steps without the need to write multiple custom tuples. I am thinking of something like:
```java
class CustomTuple {
    private Customer customer;
    private Sale sale;
    
    public CustomTuple(Customer customer) {
        this.customer = customer;
    }
    public CustomTuple(Customer customer, Sale sale) {
        this.customer = customer;
        this.sale = sale;
    }
    // getters and setters [...]
}
streams.streamAll(em, Customer.class)
    .select(c -> new CustomTuple(c))
    .join(c -> c.getCustomer().getSales())
    .select(p -> new CustomTuple(p.getOne().getCustomer(), p.getTwo))
    .toList();
```
Or maybe allow setters reusing the created object and set an attribute:
```java
streams.streamAll(em, Customer.class)
    .select(c -> new CustomTuple(c))
    .join(c -> c.getCustomer().getSales())
    .select(p -> { p.getOne().setSales(p.getTwo()); return p.getOne(); })
    .toList();
```
Or with a new method, which takes `T` of `Pair<T, U>` and applies a given setter on it with `U` as argument, mapping `JinqStream<Pair<T,U>>` to `JinqStream<T>`:
```java
streams.streamAll(em, Customer.class)
    .select(c -> new CustomTuple(c))
    .join(c -> c.getCustomer().getSales())
    .selectSet(CustomTuple::setSales)
    .toList();
```

These are just ideas, which would make the usage of this feature more convenient. If this is not possible (or too complex to implement), I'm more than happy to use your proposed custom tuples.

@ztane I think you should open a new issue regarding CI.

**Comment by my2iu** [comment]
I was a little worried about this. The Java syntax for making classes is so cumbersome that people will have no choice but to reuse classes so that they can avoid making ones. 

The scheme I've made supports multiple constructors for the same class. Just register each one separately (you don't have to register the field getters more than once though). The different constructors should have their tuples in the same order though. So you can have

```
   Constructor(arg1, arg2, arg3)
   Constructor(arg1, arg2)
```

but not

```
   Constructor(arg2, arg3)
```

I can't think of a good way to avoid having to register the constructors and getters. Jinq has to know what is safe to translate and what is not, so safe objects need to be flagged somehow. It might be possible to do something with annotations, but it would be pretty much the same.

Supporting setters would be too complicated.

**Comment by oberien** [comment]
Supporting multiple constructors already fixes the problem, as the others were only different approaches to reach the same thing.

Manually registering the classes should also be no problem if it's the easiest solution. Annotations have the advantage of not having to register everything manually, but the disatvantage of being very implicit making usage traces harder to understand without internal knowledge.

The current state looks very promising to me and I'm looking forward to the release (no stress!) :)

**Comment by my2iu** [comment]
Version 1.8.2 with support for this is now available in Maven.
