### ISSUE TITLE
Cache or Precompile queries

### ISSUE THREAD

**Issue by oberien** [my2iu/Jinq#25]
I really love the abstraction of Jinq, but the analysis of complex queries takes a lot of time compared to  JPQL-Queries or native SQL queries. Would it be possible to cache Jinq queries, which have already been analyzed, or better, to have a maven/gradle/... compiler plugin precompiling Jinq into JPQL or even already SQL?

I'm not sure on how to cache queries, i.e. how to identify them; mainly just brainstorming here :)

Precompilation could for example be done with lombok. This could mean, that queries, which should be precompiled, need to be annotated. Problems here could be (a) having queries propagating through multiple functions and (b) analyzing the "settings" of the `JinqJPAStreamProvider` (e.g. hints or [native database function mapping](https://github.com/my2iu/Jinq/issues/23) (if this will be implemented)).

**Comment by my2iu** [comment]
Queries are already cached (to the extent that it's possible given the limitations of Java 8). After analyzing a query once, the analysis is reused whenever the same sequence of lambdas are used. Performance ends up being pretty reasonable as a result. It might be possible to do some analysis at compile-time using annotation processors or something, but that's less compatible and would require me to rewrite everything.
