### ISSUE TITLE
Add automatic support for boolean getters named isField() instead of getField()

### ISSUE THREAD

**Issue by my2iu** [my2iu/Jinq#27]
Jinq currently expects boolean getters to be of the form getField() because that seemed to be the default of JPA providers. Supporting isField() requires programmers to manually register the methods with Jinq which can be annoying. 

I'll have to find an example of isField() in a JPA entity first to get a feel for how different JPA providers handle them.

**Comment by oberien** [comment]
original: #21

**Comment by my2iu** [comment]
When using JPA entities with field-based access, Jinq will now look for getters of both the form getField() and isField() for boolean fields. Jinq already did the correct thing when using JPA entities with property-based access.
