### ISSUE TITLE
Support for startsWith , contains , endsWith for String

### ISSUE THREAD

**Issue by georgemoralis** [my2iu/Jinq#29]
Currently only equals seems to be supported, I guess it is not that hard for the above methods to be added

**Comment by my2iu** [comment]
That functionality mostly exists, but it's buried in the documentation. You can find it in section "4.2 Functions" of the [Query Guide](http://www.jinq.org/docs/queries.html).

**Comment by georgemoralis** [comment]
i am not sure how that works , can you provide me with a small sample pls?

**Comment by my2iu** [comment]
```
streams.streamAll(Customer.class)
   .where( c -> c.getName().contains("Jen") )
```

**Comment by georgemoralis** [comment]
yes contains seems to work thanks :) .  For startsWith , endWIth i guess there isn't a support since i get

caused by: org.jinq.rebased.org.objectweb.asm.tree.analysis.AnalyzerException: Unknown method java/lang/String:endsWith(Ljava/lang/String;)Z encountered

Is there any plans for that? or i can do it with JPQL.like() ?  (but i don't understand how i use that...)

**Comment by my2iu** [comment]
The underlying database query language of Hibernate/EclipseLink/JPA doesn't have a function that's equivalent to startsWith() and endsWith(), so they aren't directly supported.

If you look at the list of functions that are supported, you can probably construct equivalent functionality using indexOf() and length().

JPQL.like() would also work. You should look up the LIKE function in JPQL or SQL to see what the syntax is. I think it's something like JPQL.like(s, "%th") to see if a string ends in "th".
