### ISSUE TITLE
sortedBy doesn't seem to work on runtime composition

### ISSUE THREAD

**Issue by georgemoralis** [my2iu/Jinq#33]
`JinqJPAStreamProvider streams = new JinqJPAStreamProvider(MainApp.getEmf());

        EntityManager em = MainApp.getEmf().createEntityManager();

        JinqStream<SynallassomenoiEntity> stream = streams.streamAll(em, SynallassomenoiEntity.class);

        String eponimia = eponTextField.getText();

        if (eponimia.length() > 0) {

            if (eponimiaCombo.getSelectionModel().getSelectedIndex() == 0) {

                stream = stream.where(p -> p.getName().equals(eponimia));

            }

            if (eponimiaCombo.getSelectionModel().getSelectedIndex() == 1) {

                stream = stream.where(p -> JPQL.like(p.getName(), eponimia + "%"));

            }

            if (eponimiaCombo.getSelectionModel().getSelectedIndex() == 2) {

                stream = stream.where(p -> p.getName().contains(eponimia));

            }

            if (eponimiaCombo.getSelectionModel().getSelectedIndex() == 3) {

                stream = stream.where(p -> JPQL.like(p.getName(), "%" + eponimia));

            }

        }
        stream.sortedBy(p -> p.getName());
        showndata = stream.toList();
`
it returns the list unsupported...

**Comment by aVolpe** [comment]
`sortedBy` returns a new Stream, try with `showdata = stream.sortedBy(p -> p.getName()).toList();`

**Comment by my2iu** [comment]
You'll have to include the full error message. The full error stack trace would be useful too.

**Comment by georgemoralis** [comment]
i don't have an error message just getting an unsorted list ;/

I will try what aVolpe suggests

**Comment by my2iu** [comment]
Yes, then @aVolpe is correct. It should be `stream = stream.sortedBy(p -> p.getName());`

I was confused because you wrote "list unsupported" not "list unsorted."

**Comment by georgemoralis** [comment]
it appears to work as aVolpe suggests ! 

Thank you :)
