### ISSUE TITLE
Joining entites even if not needed 

### ISSUE THREAD

**Issue by SalehAly** [my2iu/Jinq#35]
Lets say I have 3 Entities`E1, E2` and `E3` now If I create a stream that joins`E1`, `E2` and then left outer join `E3` **but only** select a pair  of `E1`, `E2`, the translated query still joins E3. 

So basically IMO it should be something like that
 
- if `E3` is (selected/used by a selected element)  then perform the join
- If `E3` was not selected but joined with other entities then
  - if the joins where **outer** and are **not** included in the selection, do not join them all
  - if the joins where **outer** and are included also in the selection, join them all
  - if the joins where **inner** then do the joins
- if `E3` is neither selected nor joined, do not perform the join

Is there a way to avoid that ?

The general idea is, to try to create a query that is a bit general, which I might us as is, or use a more  specific version of it by selecting tuned entities on API levels, other than creating several custom queries for each API call 

Example Code:
The entities join may or may not make sense but the idea is there.
```java
   @Test
   public void Test(){
      JinqStream<Tuple3<Customer,Sale,Lineorder>> customers = streams.streamAll(em, Customer.class)
           .join((val, source) -> source.stream(Sale.class))
           .where(pair -> pair.getOne().getSales().contains(pair.getTwo()))
           .select(pair -> new Pair<Customer,Sale>(pair.getOne(),pair.getTwo()))
           .leftOuterJoin(t -> JinqStream.from(t.getTwo().getLineorders()))
           .select(tuple3 -> new Tuple3<Customer, Sale, Lineorder>(tuple3.getOne().getOne(),tuple3.getOne().getTwo(),tuple3.getTwo()))
           ;


      // Now if I do a modification on this stream, and ask only for Customers and Sales
         JinqStream<Pair<Customer,Sale>> customersWithoutLineOrders =
                 customers.select(pair -> new Pair<Customer, Sale>(pair.getOne(),pair.getTwo()));
      
         String query = customersWithoutLineOrders.getDebugQueryString();

      // Now the resulting query should not include the join for Lineorders because its neither selected nor used in any further joins
      assertNotEquals("SELECT A, B FROM Customer A, Sale B LEFT OUTER JOIN B.lineorders C WHERE B IN (SELECT D FROM A.sales D)", query);

      // The resulting query should only include Customers and Sales join
      assertEquals("SELECT A, B FROM Customer A, Sale B WHERE B IN (SELECT C FROM A.sales C)", query);

   }
```

Another Example is a useless join 

```java
 JinqStream<Pair<Customer,Sale>> customers = streams.streamAll(em, Customer.class)
           .join((val, source) -> source.stream(Sale.class))
           .where(pair -> pair.getOne().getSales().contains(pair.getTwo()))
           .select(pair -> new Pair<Customer,Sale>(pair.getOne(),pair.getTwo()))
           .leftOuterJoin(t -> JinqStream.from(t.getTwo().getLineorders()))
           .select(pair -> new Pair<Customer,Sale>(pair.getOne().getOne(), pair.getOne().getTwo()))
              ;

```

**Comment by my2iu** [comment]
If you join additional tables, it changes the query results even if you don't return any elements from those additional tables. In general, Jinq can't eliminate those additional joins because it results in a different query than what you asked for.

Example:
```
CUSTOMER: 
John

SALE: 
John makes purchase A

LINEORDER: 
purchase A includes Widgets
purchase A includes Hammers
```

If I do a 
`SELECT A, B FROM Customer A JOIN SALE B`
I should get
`John, John makes purchase A`

If I do a 
`SELECT A, B, C FROM Customer A JOIN SALE B JOIN LINEORDER C`
I should get
```
John, John makes purchase A, purchase A includes Widgets
John, John makes purchase A, purchase A includes Hammers
```

If I do a 
`SELECT A, B FROM Customer A JOIN SALE B JOIN LINEORDER C`
I should get
```
John, John makes purchase A
John, John makes purchase A
```

So it would not be correct for Jinq to remove the join. The two queries ARE different, so Jinq can't optimize away the differences. In any case, I don't have the time to include an optimization such as that in Jinq. Since Jinq relies on Hibernate/EclipseLink/JPA to execute its queries, you could always ask them to implement this optimization instead, and Jinq would automatically get it.

**Comment by SalehAly** [comment]
yes, of course inner joins do change the query output, however, outer joins with no added information " not selected / used " would only add redundant data in 1:N mapping to the result set as you have showed in the example, which is in my case not needed.

But in general, it may be that someone only needs the count of the result set or whatsoever.

I thought it could be that, when the lambda stream is analyzed, unused outer joins could be removed or filtered to have a more optimized query.

Thank you

**Comment by oberien** [comment]
According to the [Postgres Changelog for Version 9.0](https://www.postgresql.org/docs/9.0/static/release-9-0.html) they eliminate unnessecary out joins in their query planner:

> Remove unnecessary outer joins (Robert Haas)
> 
> Outer joins where the inner side is unique and not referenced above the join are unnecessary and are therefore now removed. This will accelerate many automatically generated queries, such as those created by object-relational mappers (ORMs).

So when using Postgres, it would be faster for Postgres to optimize the query instead of Jinq doing it.
