### ISSUE TITLE
can just suport 'select new xxxobj()' statement ?

### ISSUE THREAD

**Issue by yangzhixiao** [my2iu/Jinq#38]
like this:

.where(xxxx)
.select(m -> new UserWalletModel(m.getId(), m.getName(), m.getWallet().getBalance()))
.toList();

as like HQL:

.createQuery("select new com.yzx.discover.model.UserWalletModel(u.id, u.name,u.wallet.balance) " +
                        "from UserEntity u " +
                        "where u.wallet.balance > :balance")
                .setParameter("balance", balance)
                .list();

**Comment by my2iu** [comment]
I actually added support for that a couple of weeks ago.

Look for "Custom Tuples" in the Query Guide:

   http://www.jinq.org/docs/queries.html
