### ISSUE TITLE
Multiple SuperTypes ignorred

### ISSUE THREAD

**Issue by Targma** [my2iu/Jinq#40]
When you extend classes with more than one @MappedSuperclass, only first one getters are put in safeMethods hash, and throws error on analyzing labda expression. In my case i try to call getId which is 2nd Superclass. 
Example:

class BaseEntity { private int; public int getId();}
class BaseVersion extend BaseEntity {...}
class Product extend BaseVersion {...}

Product is missing all functions from BaseEntity, reason for that is in file and line
https://github.com/my2iu/Jinq/blob/master/jinq-jpa/main/org/jinq/jpa/transform/MetamodelUtil.java#L360

you make new array, not sure why but you forget to include previous subClasses.
Change code 
FROM:
List<String> newSubclasses = new ArrayList<>();
newSubclasses.add(className);
findMetamodelEntityGetters(jpaObject, newSubclasses);

TO:
List<String> newSubclasses = new ArrayList<>(subclassNames);
newSubclasses.add(className);
findMetamodelEntityGetters(jpaObject, newSubclasses);

**Comment by my2iu** [comment]
Good catch! I'll try to make a new release with this fix on the weekend (or Monday/Tuesday at the latest).

**Comment by my2iu** [comment]
This fix is now available in version 1.8.13.
