### ISSUE TITLE
Unknown method java/math/BigDecimal:negate()Ljava/math/BigDecimal; encountered

### ISSUE THREAD

**Issue by georgemoralis** [my2iu/Jinq#45]
I tried the following

List<Pair<String, BigDecimal>> result2
                = streams
                        .streamAll(em, ParastatikaEntity.class)
                        .where(c -> c.getDate_created().after(from))
                        .where(c -> c.getDate_created().before(to))
                        .where(c -> c.getEidos().getTameio_affect() == 2)//pistotika
                        .where(c -> c.getSynallassomenos().getSynaltype() == 1)//gia pelates
                        .group(c -> c.getSynallassomenos().getName(), (name, stream) -> stream.sumBigDecimal(c -> c.getTotal_no_vat()).negate())
                        .toList();

Getting the following error with negate() 

Caused by: org.jinq.rebased.org.objectweb.asm.tree.analysis.AnalyzerException: Unknown method java/math/BigDecimal:negate()Ljava/math/BigDecimal; encountered
	at ch.epfl.labos.iu.orm.queryll2.symbolic.BasicSymbolicInterpreter.naryOperation(BasicSymbolicInterpreter.java:367)
	at org.jinq.rebased.org.objectweb.asm.tree.analysis.Frame.execute(Unknown Source)
	at ch.epfl.labos.iu.orm.queryll2.path.CodePath.calculateReturnValueAndConditions(CodePath.java:148)
	at ch.epfl.labos.iu.orm.queryll2.path.TransformationClassAnalyzer.analyzeMethod(TransformationClassAnalyzer.java:440)

**Comment by my2iu** [comment]
I don't think I've implemented support for negate() yet. You'll have to use something like
```new BigDecimal(0).subtract(val)```
as a workaround instead.

**Comment by georgemoralis** [comment]
tried it in a more complex query ends up with error

List<Pair<String, BigDecimal>> result2
                = streams
                        .streamAll(em, ParastatikaEntity.class)
                        .where(c -> c.getDate_created().after(from))
                        .where(c -> c.getDate_created().before(to))
                        .where(c -> c.getSynallassomenos().getSynaltype() == 1)//gia pelates
                        .group(c -> c.getSynallassomenos().getName(),
                                (name, stream) -> stream.sumBigDecimal(
                                        c -> {
                                            if (c.getEidos().getTameio_affect() == 2) {
                                                return c.getTotal_no_vat().multiply(new BigDecimal(-1));//should be c.getTotal_no_vat().negate() if it was working
                                            } else {
                                                return c.getTotal_no_vat();
                                            }
                                        }
                                ))
                        .toList();

Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: expecting "end", found '*' near line 1, column 113 [SELECT A.synallassomenos.name, SUM(CASE WHEN A.eidos.tameio_affect <> 2 THEN A.total_no_vat ELSE A.total_no_vat * -1 END) FROM prototype.parastatika.ParastatikaEntity A WHERE A.date_created > :param0 AND A.date_created < :param1 AND A.synallassomenos.synaltype = 1 GROUP BY A.synallassomenos.name]

**Comment by my2iu** [comment]
Hibernate isn't very good at doing calculations in its queries. In the past, I found that anything involving casting between types is a little flakey, and it doesn't support numeric promotion properly, so calculations involving a mix of integers, floats, decimals, etc. may or may not work. I'll try to dig deeper into this later on to see what's going on, but I suspect you may have to do something ugly like run two queries: one with Tameio_affect == 0 and another with Tameio_affect==2, and then combine the results manually in Java.

I'm making some small changes to Jinq at the moment, so I will try to add support for negate() over the weekend, but I'm not sure if that will solve your problem because Hibernate might still choke on the resulting query.

**Comment by my2iu** [comment]
I've checked-in some code for negate(). I'm going to see if I can get some support for some other features in first before I make a release though.

**Comment by georgemoralis** [comment]
my above query seems to execute correctly now in 1.8.14 thank you :)
