### ISSUE TITLE
registerAssociationAttribute does not take Inheritance into account

### ISSUE THREAD

**Issue by oberien** [my2iu/Jinq#48]
I investigated the problem @SalehAly reported [here](https://github.com/my2iu/Jinq/issues/36#issuecomment-275382338) a bit.

[SSCCE code](https://github.com/oberien/jinq-inherited-methods-sscce)

I have `SuperClass` and an extending `SubClass`. `SuperClass` has a public getter function, which I manually register using `registerAssociationAttribute`. If I stream `SubClass.class` and try to use that getter function, I'll get `AnalyzerException: Unknown method foo encountered`. Even if I register the method again on `SubClass` (which doesn't fail because the method is inherited), I still get the same error.

**Comment by my2iu** [comment]
There's actually two versions of registerAssociationAttribute(). You have to use the 4 argument version where you specifically pass in the subclass on which the method will be called. It's just a quirk of Java's reflection stuff.
