### ISSUE TITLE
bug on sortedBy().sortedBy()

### ISSUE THREAD

**Issue by ggitt** [my2iu/Jinq#50]
code

> ...streamAll(Content.class)
>                  .where(content->content.getEntityType().equals(EntityType.Book)
>                          && content.getEntityId() == entityId
>                  && content.getType().equals(NodeType.Item)).**_sortedBy(content->content.getParentId()).sortedBy(content->content.getWeight())_**
>                  .select((content)->new ContentModel(
>                          content.getId(),
>                          content.getParentId(),
>                          content.getType(),
>                          content.getTitle(),
>                          content.getContent(),
>                          content.getEntityId(),
>                          content.getEntityType(),
>                          content.getWeight(),
>                          content.getIndex()
>                          )
>                  );

is translated to:

> SELECT A FROM Content A WHERE A.entityType = com.jingfangpai.common.statics.EntityType.Book AND A.entityId = :param0 AND A.type = com.jingfangpai.common.statics.NodeType.Item **ORDER BY A.weight ASC, A.parentId ASC**

the sorting field are not in order.

**Comment by oberien** [comment]
Just for clarification reasons if someone reads this bug: From the Jinq JPA Query Guide:

> The last specified sort will become the primary sort key, the second-last specified sort will become the secondary sort key, and so on for all the specified sorting keys.
