### ISSUE TITLE
JPA 2.0 CASE WHEN

### ISSUE THREAD

**Issue by oberien** [my2iu/Jinq#53]
Is there a way to use [JPA 2.0's `CASE WHEN ELSE`](https://en.wikibooks.org/wiki/Java_Persistence/JPQL_BNF#New_in_JPA_2.0) expression? I'd like to left outer join a table on itself on a condition, but if the condition can't be satisfied (`pair.getTwo()` is `null`), I'd like to return the first element as second element as well.

If it is not supported yet, I'd like to propose the following structure:

* Create two classes called `WhenJPAJinqStream` and `ThenJPAJinqStream`.
  + `WhenJPAJinqStream` has this method:
    - `.then(element -> value)` returning `ThenJPAJinqStream`
  + `ThenJPAJinqStream` has these methods:
    - `.when(element -> condition)` returning a `WhenJPAJinqStream`
    - `.orElse(element -> value)` returning the underlying (modified) `JPAJinqStream` (`else` and `default` are Java keywords and therefore can't be used)
* Add `JPAJinqStream.ẁhen(element -> condition)` returning a `WhenJPAJinqStream`

This results in queries looking like this:

```java
streams.streamAll(Employee.class)
    .when(e -> e.salary >= 100000).then(e -> 1)
    .when(e -> e.salary < 100000).then(e -> 2)
    .orElse(e -> 0)
    .select(e -> e.getName())
```
resulting in the wiki's example query of
```sql
SELECT e.name, CASE WHEN (e.salary >= 100000) THEN 1 WHEN (e.salary < 100000) THEN 2 ELSE 0 END from Employee e
```

My requested example would look like this:
```java
streams.streamAll(User.class)
    .leftOuterJoin((u, source) -> source.stream(User.class))
    .where(p -> p.getOne().getFoo() == p.getTwo().getBar())
    .when(p -> p.getTwo() == null).then(p -> new Pair<>(p.getOne(), p.getOne()))
    .orElse(p -> new Pair<>(p.getOne(), p.getTwo()))
```

### Problems

While doing some testing I found out that apparently this JPQL Query is not valid:
```sql
SELECT A.id, CASE WHEN (B IS NULL) THEN A.id ELSE B.id END FROM Customer A LEFT OUTER JOIN Customer B ON B.id = 1337
```
The test `B IS NULL` seems to be invalid, as eclipselink fails with `'B' cannot be resolved to a type.` WInstead something like this must be used:
```sql
SELECT A.id, CASE WHEN (B.id IS NULL) THEN A.id ELSE B.id END FROM Customer A LEFT OUTER JOIN Customer B ON B.id = 1337
```

Another invalid case is the following:
```sql
SELECT A, CASE WHEN (B.id IS NULL) THEN A ELSE B END FROM Customer A LEFT OUTER JOIN Customer B ON B.id = 1337
```
It gets translated by eclipselink to the following invalid query completely leaving out `A` and `B` in `THEN` and `ELSE`:
```sql
SELECT t0.ID, t0.NAME, CASE  WHEN (t1.ID IS NULL) THEN  ELSE  END FROM CUSTOMER t0 LEFT OUTER JOIN CUSTOMER t1 ON (t1.ID = 1337)
```

I haven't tested these cases with hibernate.

**Comment by oberien** [comment]
I was able to rewrite my original issue to work without `CASE WHEN`. So while this is a nice feature to have, its priority is negligible :)

**Comment by my2iu** [comment]
Sorry, I'm having trouble unpacking what you're asking for.

CASE WHEN is already supported in Jinq. The query would look something like this:

```
streams.streamAll(Employee.class)
   .select(e -> {
      String name = e.getName();
      int val;
      if (e.getSalary() >= 100000)
         val = 1;
      else 
         val = 2;
      return new Pair<String, Integer>(name, val);
   });
```

I'm not sure about the JPQL problems that you listed.

**Comment by oberien** [comment]
Wow, I didn't expect Jinq to take into account if-else inside lambdas, that works :100:

Unfortunately the other two bugs exist but are either JPA or eclipselink related, so nothing for you to fix. Just for your information take this rewritten example:

```java
streams.streamAll(User.class)
    .leftOuterJoin((u, source) -> source.stream(User.class),
        (u1, u2) -> u2 == null || u1.getFoo() == u2.getBar())
    .select(p -> new Pair<>(p.getTwo() != null ? p.getTwo() : p.getOne()))
```
It gets translated correctly into

```sql
SELECT A, CASE WHEN B IS NOT NULL THEN B ELSE A END FROM User A LEFT OUTER JOIN User B ON B IS NULL OR A.foo = B.bar
```
But eclipselink reports `'B' cannot be resolved to a type.` refering to the B after `WHEN`.

I can use `p.getTwo().getId()` instead in the condition to resolve that problem, but that leaves me with invalid SQL produced by eclipselink:

```sql
Call: SELECT [t0.everything], CASE  WHEN (t1.ID IS NOT NULL) THEN  ELSE  END FROM USERS t0 LEFT OUTER JOIN USERS t1 ON ((t1.ID IS NULL) OR (t0.FOO = t1.BAR))
```

As you can see there is nothing behind `THEN` and `ELSE`. But again, nothing Jinq can do anything about, so I'm going to close this issue.
