### ISSUE TITLE
 org.hibernate.SessionFactory.getAllClassMetadata is no longer supported in Hibernate 5.2.*

### ISSUE THREAD

**Issue by SpringRen** [my2iu/Jinq#54]
please use method getMetamodel instead……

**Comment by my2iu** [comment]
I'll try to study this soon. I don't want to break compatibility with older versions of Hibernate, so I need to see what changed and how to support it.

**Comment by my2iu** [comment]
I think I've fixed it. The 5.2, the Hibernate factory is compatible with the JPA entity manager factory, so I was able to reuse the existing JPA code to handle it. 

I'll try to make a release with this change on Monday.

I'm not 100% sure if that's the only change between 5.2 and 5.1 though. If you encounter other problems, please let me know.

**Comment by my2iu** [comment]
Jinq 1.8.18 with better support for Hibernate 5.2 is now released.

**Comment by SpringRen** [comment]
tks a lot ,it,s helpfull to me!
