### ISSUE TITLE
EXISTS

### ISSUE THREAD

**Issue by my2iu** [my2iu/Jinq#55]
Add a way to generate EXISTS queries because it's faster for some databases.

**Comment by lvv83** [comment]
Hello. Is there any plan about this feature?

**Comment by my2iu** [comment]
I didn’t have any particular plans for it, but if you need the feature, then I can try to take a look later this month.

**Comment by lvv83** [comment]
I would appreciate for this. Thank you!

**Comment by my2iu** [comment]
Just a reference note about EXISTS queries in JPQL so it's easy to find later:

https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#exists-expressions

**Comment by my2iu** [comment]
I've added an .exists() method to streams that will be translated into EXISTS subqueries. I've built new Maven versions with support for this, but I still need to work on documentation fixups and updating the website.

**Comment by my2iu** [comment]
Documentation has now been updated, so support for exists() should now be complete.
