### ISSUE TITLE
Scala sample could be improved

### ISSUE THREAD

**Issue by mkotsbak** [my2iu/Jinq#6]
def customers(): JinqIterator[Customer] = { return streams.streamAll(em, classOf[Customer]); }  

could be replaced by:

def customer = streams.streamAll(em, classOf[Customer]) etc. and remove the () in the uses:
customers.foreach( c => println(c.getName() + " " + c.getCountry() + " " + c.getSalary()));

(or use s"")

**Comment by my2iu** [comment]
Good point. That code is so Java that it's a little embarrassing. I've made a new release 1.7.1 with updates to the sample code, fixes to sumBigDecimal/sumBigInteger, and which brings the Scala code up to feature parity with the Java code with support for contains() and joinFetch().
