### ISSUE TITLE
Add support for java.time package

### ISSUE THREAD

**Issue by jeffjedi** [my2iu/Jinq#62]
I'm using Jinq to implement a complex filter in a Spring Boot application and most of it is doing fine.
However my entities are all mapped using java.time package when it comes do Date and Time fields.
I kindly request that you enhance JinQ to support methods like isAfter and isBefore (and maybe even Period.isBetween) just like it does today but for the following main objects used for mapping:
`java.time.LocalDate,
java.time.LocalDateTime,
java.time.LocalTime`

Thx.

**Comment by my2iu** [comment]
This is a limitation of JPQL. As far as I know, Hibernate and EclipseLink don't support the new Java 8 time stuff, so Jinq cannot generate Hibernate/EclipseLink queries that use them in queries.

**Comment by jeffjedi** [comment]
We use Hibernate @ 5.2.10.Final which supports those fully, no converters, and even generates the whole schema following diallect class.
In MySQL 5.7 it uses DATETIME for LocalDateTime and DATE for LocalDate. It does the same for SQL Server 2008 & 2014, only specifying length for DATETIME type.
I totally understand that not everyone is dealing with such new stacks as the ones I mentioned.
However please consider adding this enhancement to JinQ as it is such an awesome tool and it would be great to keep pushing it to newer tools releases like Hibernate and Spring Boot.
I also understand that there's no easy way out as JPA still doesn't specify those types (and we have to use them without the TEMPORAL annotation) and my use case is entirely specific to Hibernate implementation only.

Thx.

**Comment by my2iu** [comment]
Does Hibernate actually support using LocalDateTime in JPQL/HQL queries yet though? Without support for that, Jinq can't do anything.

**Comment by jeffjedi** [comment]
Yes it does, if you start a Spring Boot app with JPA and add Hibernate 5.2.10.Final (core and entity manager) to its dependencies you're good to go. 
Schema creation and all. 
You map those properties without using the Temporal annotation and then use JPA repository from Spring. 
Any query custom or by implying via method name, you can use the java.time package as targets or parameters of them.

Thx

**Comment by my2iu** [comment]
I'll take a look then.

**Comment by my2iu** [comment]
I've added support for this. I'll need to think about whether/how the documentation needs to change before making a new release with the new code.

**Comment by jeffjedi** [comment]
Thank you very much @my2iu 

I was trying to find you a link for their documentation regarding this, but since you already added code and I couldn't find it, here's the next best thing:
https://hibernate.atlassian.net/browse/HHH-8844

That's the issue which started the enhancement on their side
The initial implementation section in its description is consistent with my testing using version 5.2.10.Final which describes the SQL Types they consider for mapping purposes and that is accurate information

Thx for all!

**Comment by my2iu** [comment]
Jinq version 1.8.20 with support for Hibernate 5.2's java.time support is now available in Maven if you need it. I'll need a couple of days to do the documentation and to update the website though.
