### ISSUE TITLE
Jinq+envers : NullPointerException in MetamodelUtilFromMetamodel.entityNameFromClassName()

### ISSUE THREAD

**Issue by Dagarth** [my2iu/Jinq#63]
Hi,
envers, generates audit tables which appears in metamodel but got null javaType.

In this method we got : entity.getJavaType().getName() throwing NPE.

Could you add null check here ?

**Comment by my2iu** [comment]
I've released a new version 1.8.21 on Maven only (not on the Jinq website) that has this fix.
