### ISSUE TITLE
can not return muti-fileds 

### ISSUE THREAD

**Issue by SpringRen** [my2iu/Jinq#65]
i want to select muti-fileds…… 
like this expression :     
`.select(c ->Tuple.createTuple(new Object[]{c.getId(),c.getRemark(),c.getSrc(),c.getStatus()})).toList()`,
but it,s not work.
here is the logs:
`java.lang.IllegalArgumentException: Could not analyze lambda code  at org.jinq.jpa.transform.LambdaAnalysis.fullyAnalyzeLambda(LambdaAnalysis.java:197)`

**Comment by my2iu** [comment]
The correct syntax for creating a 4-element tuple is

```
.select(c -> new Tuple4<>(c.getId(),c.getRemark(),c.getSrc(),c.getStatus())
.toList()
```

I guess I can add better documentation about this in the query guide. I'll do that later.

**Comment by my2iu** [comment]
The Jinq documentation has now been updated with more information about how to use tuples.
