### ISSUE TITLE
how to use postgresql's keyword ilike

### ISSUE THREAD

**Issue by ychost** [my2iu/Jinq#66]
i want to do  "case insensitive" search, i use postgressql and i find that org.hibernate.criterion.Restrictions has a "ilike" method but  not find in JPQL. i want use in jinq ,shoud i do?

**Comment by my2iu** [comment]
You could do something like 
```
.where( c -> JPQL.like(c.getName().toUpperCase(), "A%")
```
But that might be slow depending on whether your database is able to use its indices correctly for the query or not. Case insensitive search in general might be slow depending on how the database is configured. In some cases, you can set-up the indices for your database column to default to case-insensitive searches.
