### ISSUE TITLE
Support returning Iterable, as Spring JPA

### ISSUE THREAD

**Issue by mkotsbak** [my2iu/Jinq#7]
It probably would be nice if, in addition to the ".iterator()", it would be supported a ".iterable()" that return a Iterable as result, as is possible with JPA with Spring.

**Comment by my2iu** [comment]
I don't understand what you're asking for here. The Java version of Jinq doesn't use iterators (the Scala version does, but that's because the Scala's iterator has a lot more features available that lets it behave like a stream). When you call toList(), results are converted to an Iterable.

**Comment by my2iu** [comment]
Is this about the Scala version of Jinq? If it is, the results are Scala iterators, so Scala provides a toIterable() method on those. It returns a Scala Iterable and not a Java Iterable though. But Scala probably has some sort of autoconversion rule you can import that can convert Scala Iterables to Java Iterables automatically somehow.

**Comment by mkotsbak** [comment]
No, it's with Java 8. Ah, I'm sorry, I see that the Java List is actually an Iterable, so .toList() would suffice.
