### ISSUE TITLE
java.util.UUID not supported

### ISSUE THREAD

**Issue by JGasp** [my2iu/Jinq#70]
I would like to see java.util.UUID added to supported types.

**Comment by my2iu** [comment]
What do you mean by UUID? A SQL UUID? A Hibernate UUID? Are you representing your UUID in Java as Strings or as UUID objects?

**Comment by JGasp** [comment]
`` @Id
    @Column(name = "id", columnDefinition = "uuid", updatable = false)
    private UUID id;``

**Comment by my2iu** [comment]
I've released a version 1.8.23 to Maven that has support for UUID. It seems to work with Hibernate, but I haven't had much luck getting it to work with EclipseLink. I'll update the website with the release later in the week.
