### ISSUE TITLE
hi,guys,is jinq dead?

### ISSUE THREAD

**Issue by zhxjdwh** [my2iu/Jinq#74]

**Comment by my2iu** [comment]
The code works, contains most major pieces of needed functionality, and has fallbacks for cases that it can't handle. So there's no need to make any major changes to the project currently. There's no funding for any large scale new development work on the project, but I still try to keep it up-to-date and running on the latest versions of the Java. Obviously, it would be better if there were a similar project with constant development happening on it. But there aren't too many people interested in LINQ for Java, there are only a few people in the world with the expertise needed to code up a project like this, and no one wants to dedicate the resources to build their own version. So this project is pretty much the only choice available if you need its specific set of features.
