### ISSUE TITLE
Java 13 supported?

### ISSUE THREAD

**Issue by Flying--Dutchman** [my2iu/Jinq#89]
Is the current Jinq release compatible with Java 13?

**Comment by my2iu** [comment]
Possibly. I updated the underlying bytecode libraries to ones that support Java 14 last week, but I haven’t bothered downloading Java 13 or Java 13 compatible versions of Hibernate to test.

**Comment by Flying--Dutchman** [comment]
I'm running Java 13 and I didn't run into any errors so far.

Would like to thank you very much for this library. As somenone who comes from the C# and LINQ world, this library is godsend. You did an amazing job, thank you!
